### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by Mihailstoica350** [b-r-o/FrameExtractor#1]
Hey! Thanks for this amazing git.
I have a question, if I want to stack every image into an array, I'll run quickly into a memory issue. Any suggestion?

**Comment by b-r-o** [comment]
Hey, you don't build an array of images because they will all be in memory. Instead, you save the image somewhere and you build an array of paths to those images

On 1 Aug 2018, at 12:36 PM, Mihailstoica350 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey! Thanks for this amazing git.
I have a question, if I want to stack every image into an array, I'll run quickly into a memory issue. Any suggestion?

**Comment by Mihailstoica350** [comment]
Thanks for your fast response!
But if you want to save the image at a path, you need to first convert the image in DATA which will also lead to a memory issue.

I'm working on a project where I need to save the all the images generated in an interval of 5 seconds, I will appreciate a response.

**Comment by b-r-o** [comment]
Don't underestimate the impact on the memory of images. Why don't you save a movie instead? Do you need to do some image processing after or do you just want to replay what you recorded?

Writing to disk will add an overhead but you can offset it to a background thread and queue all the disk writing over there, freeing your capturing thread

On 1 Aug 2018, at 12:42 PM, Mihailstoica350 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your fast response!
But if you want to save the image at a path, you need to first convert the image in DATA which will also lead to a memory issue.

I'm working on a project where I need to save the images for 5 seconds, I will appreciate a response.

**Comment by Mihailstoica350** [comment]
Yes, I need to do some image processing afterwards and making a video won’t
help. Thank you!

**Comment by Mihailstoica350** [comment]
I tried to do it on the background thread but the app still crashes due to memory issue :(. Can you give me an example of code? Thanks again for the response
